#! /bin/bash
#
# kismet_ctl - script to switch kismet on/off
#                  (usually called from the WLANPi menu system)    
#
# Written by Nigel Bowden <wifinigel@gmail.com>.
#
# History:
#
# v0.01 - 31st July 2019 - initial version
# v0.02 - 1st Aug 2019   - fixed path issue in version info

set -e

NAME=kismet_ctl
HOME_DIR=/home/wlanpi/nanohat-oled-scripts
DESC="Script to switch kismet on/off"
VERSION=0.02

if [[ $EUID -ne 0 ]]; then
   echo "This script must be run as root" 
   exit 1
fi

###############################################################################
#
# Launch kismet:
#
###############################################################################
kismet_start () {
  # If already running, do nothing & return message
  if ! [ -z `pidof kismet` ]; then
    echo "Kismet is running."
    return
  fi
  
  # Launch Kismet as background process (as the wlanpi user)
  # (Output sent to /dev/null so that interactive process returns and
  # doesn't hang calling script)
  su -c '/usr/local/bin/kismet > /dev/null 2>&1 &' - wlanpi
    
  # Signal that kismet active
  echo "Kismet start initiated."

}

###############################################################################
#
# Kill kismet:
#
###############################################################################
kismet_stop () {
  # Check Kismet is running and kill it
  if ! [ -z `pidof kismet` ]; then
    echo "Killing Kismet process"
    kill `pidof kismet`
  else
    echo "Kismet not running"
    return
  fi
  
  # Kismet docs also recommend restarting networking when Kismet
  # stops, so we'll do that for good measure (silently)
  sudo service networking restart
}

###############################################################################
#
# Return kismet status:
#
###############################################################################
status () {
  # Check if we see the kismet process and report positive or negative message
  if ! [ -z `pidof kismet` ]; then
    echo "Kismet is running"
  else
    echo "Kismet not running"
    return
  fi
}

is_running () {
    #Binary 0/1 to indicate if process running
    if ! [ -z `pidof kismet` ]; then
        return 1
    else
        return 0
    fi

}

###############################################################################
#
# Return script version:
#
###############################################################################
version () {
    N=$HOME_DIR/$NAME
        echo "Version: $N $VERSION" >&2
        exit 1

}

case "$1" in
  start)
        kismet_start
        ;;
  stop)
        kismet_stop
        ;;
  status)
        status
        ;;
  is_running)
        is_running
        ;;
  version)
        version;;
  *)
        N=$HOME_DIR/$NAME
        echo "Usage: $N {start|stop|status|is_running|version}" >&2
        exit 1
        ;;
esac

exit 0

